spring.application.name=start
app.name=@project.artifactId@
app.version=@project.version@

azure.application-insights.connection-string=${APPLICATIONINSIGHTS_CONNECTION_STRING}
azure.application-insights.enabled=true
# Ensure your logging level is set
logging.level.root=INFO
logging.level.com.microsoft.applicationinsights=INFO
